#!/bin/bash

if ifinstalled; then
	ifinstalled maim imagemagick tesseract xclip || exit
fi

readonly TESSDATA_PREFIX=${TESSDATA_PREFIX:-~/.local/share/tessdata/}
readonly TESS_LANG=${TESS_LANG:-eng}
export TESSDATA_PREFIX
export IFS="+"

ocr() {
	# https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html#missing-borders
	maim --select --hidecursor --format=png --quality 1 |
	convert png:- -monochrome -alpha off -bordercolor White -border 10x10 png:- |
	tesseract stdin stdout \
		-l "$TESS_LANG" \
		--tessdata-dir "$TESSDATA_PREFIX" |
		grep -P '[A-z 0-9]+'
}

notify() {
	echo "$*"
	notify-send "Maim OCR" "$*"
}

main() {
	for lang in $TESS_LANG; do
		if ! [[ -f "$TESSDATA_PREFIX/$lang.traineddata" ]]; then
			notify "No trained data found."
			exit 1
		fi
	done

	local -r result=$(ocr)

	if [[ -n $result ]]; then
		xclip -selection clipboard <<< "$result"
		notify "$result"
	else
		notify "Failed."
	fi
}

main
