#!/bin/bash
pnpm init
pnpm add -D ts-node-dev typescript @types/node@"*" eslint concurrently husky lint-staged eslint-config-prettier prettier
./node_modules/.bin/eslint --init
git init
pnpm tsc --init
npx husky install
npx husky add .husky/pre-commit "pnpm validate:check-types && pnpm lint-staged && pnpm validate:build"

cat >tsconfig.json <<EOL
  {
    "compilerOptions": {
      "module": "commonjs",
      "target": "es2016",
      "noImplicitAny": true,
      "strictNullChecks": true,
      "moduleResolution": "node",
      "sourceMap": true,
      "outDir": "build",
      "baseUrl": ".",
      "rootDirs": [
        "src/"
      ],
      "types": [
        "node"
      ]
    },
    "include": [
      "src/**/*"
    ]
  }
EOL

mkdir -p src
cat >src/index.ts <<EOL
  console.log('hello world!');
EOL

sed -i 's/"test".*"/\"dev\": \"ts-node-dev --respawn --transpile-only src\/index.ts\",\n\t\"build\": \"tsc --build\",\"start\": \"node .\/build\/index.js\",\n\t\"prettier\": \"prettier --ignore-path .gitignore \\"**\/*.+(js|json|ts|tsx)\\"\",\n\t\"format\": \"pnpm prettier --write\",\n\t\"validate\": \"concurrently pnpm:validate:*\",\n\t\"validate:check-types\": \"tsc\",\n\t\"validate:check-format\": \"pnpm prettier --list-different\",\n\t\"validate:lint\": \"eslint --ignore-path .gitignore --ext .js,.ts,.tsx .\",\n\t\"validate:build\": \"tsc --build\",\n\t\"prepare\": \"husky install\"/g' package.json

touch .lintstagedrc.json
cat >.lintstagedrc.json <<EOL
{
  "*.+(js|jsx|ts|tsx)": ["eslint"],
  "**/*.+(js|json|ts|tsx)": ["prettier --write", "git add"]
}
EOL

sed -i 's/"plugin.*ded"/\n\t\"plugin:@typescript-eslint\/recommended\",\n\t\"prettier"/g' .eslintrc.json

touch .gitignore
cat >.gitignore <<EOL
/node_modules/
/build/
*.log
EOL

pnpm prepare
